# Generated by Django 4.2.6 on 2023-10-29 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_fullname_employee_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='eid',
        ),
    ]
